spring.application.name=KnockIn

spring.profiles.active=test
spring.profiles.include=secret-common

spring.profiles.group.prod=secret-prod
spring.profiles.group.test=secret-test

springdoc.use-fqn=true
popular.count.size=10

policy.board.comeable-date-visible-grace-days=7
policy.board.image-max-count=10
policy.board.thumbnail-image-max-count=1

policy.chat.room-limit-per-member=15

policy.request-alarm.expire-days=7

policy.roommate-score.perfect-score=100
policy.roommate-score.important-pattern-multiplier=2
