spring.application.name=KnockIn

spring.profiles.active=test
spring.profiles.include=secret-common

spring.profiles.group.prod=secret-prod
spring.profiles.group.test=secret-test

springdoc.use-fqn=true
popular.count.size=10