package org.example.knockin.repository;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;

@DisplayName("H2 CHECK 제약식 회귀 테스트")
class H2CheckConstraintRegressionTest {

    private static final String DATABASE_URL =
            "jdbc:h2:mem:h2_check_constraint_regression;DB_CLOSE_DELAY=-1";

    @Test
    @DisplayName("제약식을 생성한 세션이 닫혀도 다른 세션에서 허용된 discriminator를 저장한다")
    void insertAllowedDiscriminatorFromDifferentSession() throws Exception {
        try (Connection schemaConnection = DriverManager.getConnection(DATABASE_URL, "sa", "");
             var statement = schemaConnection.createStatement()) {
            statement.execute("""
                    create table room_profile (
                        id bigint generated by default as identity primary key,
                        type varchar(31) not null
                            check (type in ('RoomProfile', 'OFFER', 'SEEKER'))
                    )
                    """);
        }

        assertDoesNotThrow(() -> {
            try (Connection insertConnection = DriverManager.getConnection(DATABASE_URL, "sa", "");
                 var statement = insertConnection.prepareStatement(
                         "insert into room_profile (type, id) values ('SEEKER', default)")) {
                assertEquals(1, statement.executeUpdate());
            }
        });
    }
}
